### ISSUE TITLE
Avoid overflows to avoid panic

### ISSUE THREAD

**Issue by dfquaresma** [gcinterceptor/gci-go#1]
Looking at the worst scenario, some integer variables could overflow while GCI run. _Counters_ around the code and the variables **incoming** and **finished**, in interceptor.go file, are examples of it. 
One solution for it would be turn them for zero at some moment. To **incoming** and **finished** it could be done after each GC execution.

**Comment by danielfireman** [comment]
Also, a great time to start adding tests. Those test scenarios are could be used when porting GCI to other runtimes.
