### ISSUE TITLE
Possible bug in queue size calculation 

### ISSUE THREAD

**Issue by dfquaresma** [gcinterceptor/gci-go#11]
I may be wrong, but I believe that we should calculate the queue size doing **incoming - finished**. If we have 2 requests in queue and no request was attended, **incoming is 2** and **finished is 0**, so the **queue size is 2**.  

link where that calculation is made: https://github.com/gcinterceptor/gci-go/blob/master/gccontrol/interceptor.go#L104

link of the method called: https://github.com/gcinterceptor/gci-go/blob/master/gccontrol/unavailability.go#L49

**Comment by danielfireman** [comment]
That sounds reasonable to me. Re-opening the issue so I can fix it.
