### ISSUE TITLE
Not needed fit in sampler update

### ISSUE THREAD

**Issue by dfquaresma** [gcinterceptor/gci-go#12]
Again, I might be wrong, but I believe that there is no reason to we still use **lastFinished** since we are turning to zero the **finished** variable at interceptor. 
A possible incoherence of doing that it's have a negative **curr** at sampler, if **lastFinished** is bigger than **finished**. We used that subtraction to know how much requests was finished because we wasn't turning **finished** to zero. Now, **finished** has the value we need.   
I also believe that it can **increase the collects** since that difference is smaller than needed. 
So here https://github.com/gcinterceptor/gci-go/blob/master/gccontrol/sampler.go#L45 we could do s.past[s.next] = finished.

**Comment by danielfireman** [comment]
Great catch. Re-opening so I can fix it.

**Comment by danielfireman** [comment]
This has been fixed by bc3e5f350e95e4c48c4bd2cbd65b121289b555ae
